apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-application
  template:
    metadata:
      labels:
        app: react-application
    spec:
      containers:
      - name: react-application
        image: <your-image-name>
        ports:
        - containerPort: 3000
