apiVersion: v1
kind: Service
metadata:
  name: react-application-service
spec:
  selector:
    app: react-application
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 3001
      nodePort: 30080
  type: LoadBalancer
