apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsimage
spec:
  selector:
    matchLabels:
      app: nodejsimage
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejsimage
    spec:
      containers:
      - name: nodejscont
        image: gdeiley/csc468:latest
        ports:
        - containerPort: 3000
