apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejsimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsimage
  template:
    metadata:
      labels:
        app: nodejsimage
    spec:
      containers:
      - name: nodeserver
        image: gdeiley/nodejsimage:latest
        ports:
        - containerPort: 3000
